export default {
    PE: 'Pergunto',
    SU: 'Sugiro',
    AD: 'Além disso',
    CM: 'Comento',
    ACT: 'Acrescento',
    INF: 'Informo',
    RP: 'Respondo',
    CD: 'Concordo',
    DIS: 'Discordo',
    PRQ: 'Para que',
    PQ: 'Porque',
    PC: 'Peço',
    EX: 'Explico',
    EXF: 'Exemplifico',
    NE: 'Não entendi',
    E: 'E',
    ET: 'Então',
    OU: 'Ou',
    MAS: 'Mas',
    CNM: 'Concordo mas',
    DSM: 'Discordo mas',
    CON: 'Continuo',
    TRN: 'Transcrevo',
}