const KIND_OF_SPEECH_CHOICES = [
    { key: 'PE', text: 'Pergunto' },
    { key: 'SU', text: 'Sugiro' },
    { key: 'AD', text: 'Além disso' },
    { key: 'CM', text: 'Comento' },
    { key: 'ACT', text: 'Acrescento' },
    { key: 'INF', text: 'Informo' },
    { key: 'RP', text: 'Respondo' },
    { key: 'CD', text: 'Concordo' },
    { key: 'DIS', text: 'Discordo' },
    { key: 'PRQ', text: 'Para que' },
    { key: 'PQ', text: 'Porque' },
    { key: 'PC', text: 'Peço' },
    { key: 'EX', text: 'Explico' },
    { key: 'EXF', text: 'Exemplifico' },
    { key: 'NE', text: 'Não entendi' },
    { key: 'E', text: 'E' },
    { key: 'ET', text: 'Então' },
    { key: 'OU', text: 'Ou' },
    { key: 'MAS', text: 'Mas' },
    { key: 'CNM', text: 'Concordo mas' },
    { key: 'DSM', text: 'Discordo mas' },
    { key: 'CON', text: 'Continuo' },
];

export default KIND_OF_SPEECH_CHOICES;